GET http://localhost:3001/api/persons

GET http://localhost:3001/api/persons/1

GET http://localhost:3001/api/info

GET http://localhost:3001/api/persons/10

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json
Authorization: token xxx

{
    "name": "Dan Abramov",
    "number": "040-123456"
}